# Generated by Django 4.2.4 on 2023-08-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='upload/')),
                ('ingredients', models.TextField()),
                ('minutes', models.IntegerField()),
                ('calories', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=2000)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeApp.tag')),
            ],
        ),
    ]
