# Generated by Django 4.2.4 on 2023-08-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_remove_recipe_ingredients_recipe_owner_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
