# Generated by Django 4.2.4 on 2023-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0003_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
