# Generated by Django 4.2.4 on 2023-08-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0008_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='qty',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
