# Generated by Django 4.2.4 on 2023-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0010_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='qty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
