# Generated by Django 4.2.4 on 2023-08-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0014_review_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
