# Generated by Django 4.2.4 on 2023-08-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0016_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
