# Generated by Django 4.2.4 on 2023-08-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0019_article_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='uploader',
        ),
    ]
